// High-level wrapper classes over the arborium-rt ABI.

import {
    ABI_VERSION,
    ArboriumError,
    putUtf8,
    readUtf8,
    resolveWasm,
    type HostModule,
    type HostModuleFactory,
    type RuntimeAbi,
    type WasmSource,
} from './abi.js';
import type { Utf16ParseResult } from './types.js';

/** Options for {@link loadArboriumRuntime}. */
export interface LoadArboriumRuntimeOptions {
    /**
     * Factory produced by emscripten's MODULARIZE output. In this package, import
     * it from `@discord/arborium-rt/host-module`; in dev, import the built
     * `target/host-wasm/web-tree-sitter.mjs` directly.
     */
    hostModuleFactory: HostModuleFactory;
    /** Bytes of `arborium_emscripten_runtime.wasm` (SIDE_MODULE=2). */
    runtimeWasm: WasmSource;
    /** Optional overrides forwarded to the emscripten factory (e.g. `locateFile`). */
    hostModuleOverrides?: Partial<HostModule>;
}

/**
 * Load the host wasm and the arborium-rt SIDE_MODULE into it. Verifies the ABI
 * version. Throws {@link ArboriumError} with `kind: 'abi-mismatch'` on
 * version skew.
 */
export async function loadArboriumRuntime(
    options: LoadArboriumRuntimeOptions,
): Promise<Runtime> {
    const host = await options.hostModuleFactory(options.hostModuleOverrides);
    const runtimeBytes = await resolveWasm(options.runtimeWasm);
    const abi = (await host.loadWebAssemblyModule(runtimeBytes, {
        loadAsync: true,
    })) as unknown as RuntimeAbi;
    const actual = abi.arborium_rt_abi_version();
    if (actual !== ABI_VERSION) {
        throw new ArboriumError(
            'abi-mismatch',
            `arborium-rt ABI version mismatch: package targets ${ABI_VERSION}, runtime reports ${actual}`,
        );
    }
    return new Runtime(host, abi);
}

/** Options for {@link Runtime.loadGrammar}. */
export interface LoadGrammarOptions {
    /** Bytes / URL of `tree-sitter-<lang>.wasm` (SIDE_MODULE=2). */
    wasm: WasmSource;
    /** Contents of `highlights.scm`. Required — a grammar with no highlights is useless. */
    highlights: string;
    /** Contents of `injections.scm`, if the grammar supports language injection. */
    injections?: string;
    /** Contents of `locals.scm`, if the grammar uses local-scope queries. */
    locals?: string;
    /**
     * Name of the grammar's `tree_sitter_<lang>()` export. If omitted, the
     * loader auto-detects by scanning the module's exports for a single
     * function starting with `tree_sitter_`.
     */
    languageExport?: string;
}

/**
 * Stable shape emitted by `@arborium-rt/<lang>` grammar packages. Any
 * package whose default export satisfies this interface can be handed
 * straight to {@link Runtime.loadGrammar}: it's structurally assignable
 * to {@link LoadGrammarOptions}.
 *
 * Generated by `scripts/build-grammar-package.py`.
 */
export interface ArboriumGrammarPackage {
    /** Grammar id from `arborium.yaml` (e.g. `"json"`, `"typescript"`). */
    languageId: string;
    /** Symbol the grammar wasm exports (always `"tree_sitter_<languageId>"`). */
    languageExport: string;
    /** URL to the grammar SIDE_MODULE wasm, resolved against the package. */
    wasm: URL;
    /** Flattened highlights query (prepend chain + own). */
    highlights: string;
    /** Flattened injections query, if the grammar defines one. */
    injections?: string;
    /** Flattened locals query, if the grammar defines one. */
    locals?: string;
}

/**
 * A loaded arborium runtime. One per host module. Manages zero or more
 * {@link Grammar}s, each of which can spawn zero or more {@link Session}s.
 */
export class Runtime {
    /** The underlying host module — exposed for consumers that need raw access. */
    readonly host: HostModule;
    /** Raw ABI exports — exposed for debugging / advanced use. */
    readonly abi: RuntimeAbi;

    /** @internal */
    constructor(host: HostModule, abi: RuntimeAbi) {
        this.host = host;
        this.abi = abi;
    }

    /** Register a grammar. Returns a {@link Grammar} handle. */
    async loadGrammar(options: LoadGrammarOptions): Promise<Grammar> {
        const grammarBytes = await resolveWasm(options.wasm);
        const grammarExports = await this.host.loadWebAssemblyModule(grammarBytes, {
            loadAsync: true,
        });
        const languageFn = pickLanguageExport(grammarExports, options.languageExport);
        const langPtr = (languageFn as () => number)();
        if (!langPtr) {
            throw new ArboriumError(
                'grammar-registration-failed',
                'grammar tree_sitter_* export returned null',
            );
        }
        const [hPtr, hLen] = putUtf8(this.host, options.highlights);
        const [iPtr, iLen] = putUtf8(this.host, options.injections ?? '');
        const [lPtr, lLen] = putUtf8(this.host, options.locals ?? '');
        let grammarId = 0;
        try {
            grammarId = this.abi.arborium_rt_register_grammar(
                langPtr,
                hPtr, hLen,
                iPtr, iLen,
                lPtr, lLen,
            );
        } finally {
            if (hPtr) this.host._free(hPtr);
            if (iPtr) this.host._free(iPtr);
            if (lPtr) this.host._free(lPtr);
        }
        if (grammarId === 0) {
            throw new ArboriumError(
                'grammar-registration-failed',
                'arborium_rt_register_grammar returned 0 (query compile failure?)',
            );
        }
        return new Grammar(this, grammarId, langPtr);
    }
}

/**
 * A registered grammar. Spawn sessions with {@link Grammar.createSession}.
 * Call {@link Grammar.unregister} when done; any sessions still open are torn
 * down as part of unregistration.
 */
export class Grammar {
    readonly runtime: Runtime;
    readonly id: number;
    /** The `*const TSLanguage` this grammar owns in shared memory. */
    readonly languagePtr: number;
    #unregistered = false;

    /** @internal */
    constructor(runtime: Runtime, id: number, languagePtr: number) {
        this.runtime = runtime;
        this.id = id;
        this.languagePtr = languagePtr;
    }

    createSession(): Session {
        this.#assertLive();
        const sessionId = this.runtime.abi.arborium_rt_create_session(this.id);
        if (sessionId === 0) {
            throw new ArboriumError(
                'session-creation-failed',
                `arborium_rt_create_session(${this.id}) returned 0`,
            );
        }
        return new Session(this, sessionId);
    }

    unregister(): void {
        if (this.#unregistered) return;
        this.runtime.abi.arborium_rt_unregister_grammar(this.id);
        this.#unregistered = true;
    }

    #assertLive(): void {
        if (this.#unregistered) {
            throw new ArboriumError(
                'grammar-registration-failed',
                `grammar ${this.id} has been unregistered`,
            );
        }
    }
}

/**
 * A parser session — a per-document stream of `setText`/`parse` calls.
 * Sessions are cheap; create one per document/viewer. Always {@link Session.free}
 * when done, or call {@link Grammar.unregister} to tear down en masse.
 */
export class Session {
    readonly grammar: Grammar;
    readonly id: number;
    #freed = false;

    /** @internal */
    constructor(grammar: Grammar, id: number) {
        this.grammar = grammar;
        this.id = id;
    }

    setText(text: string): void {
        this.#assertLive();
        const [ptr, len] = putUtf8(this.grammar.runtime.host, text);
        try {
            this.grammar.runtime.abi.arborium_rt_set_text(this.id, ptr, len);
        } finally {
            if (ptr) this.grammar.runtime.host._free(ptr);
        }
    }

    parse(): Utf16ParseResult {
        this.#assertLive();
        const { host, abi } = this.grammar.runtime;
        const outPtrSlot = host._malloc(4);
        const outLenSlot = host._malloc(4);
        try {
            const rc = abi.arborium_rt_parse_utf16(this.id, outPtrSlot, outLenSlot);
            if (rc !== 0) {
                throw new ArboriumError(
                    'parse-failed',
                    `arborium_rt_parse_utf16 returned status ${rc}`,
                );
            }
            const jsonPtr = host.getValue(outPtrSlot, 'i32');
            const jsonLen = host.getValue(outLenSlot, 'i32');
            if (jsonLen === 0) {
                return { spans: [], injections: [] };
            }
            try {
                const json = readUtf8(host, jsonPtr, jsonLen);
                return JSON.parse(json) as Utf16ParseResult;
            } finally {
                abi.arborium_rt_free(jsonPtr, jsonLen);
            }
        } finally {
            host._free(outPtrSlot);
            host._free(outLenSlot);
        }
    }

    cancel(): void {
        this.#assertLive();
        this.grammar.runtime.abi.arborium_rt_cancel(this.id);
    }

    free(): void {
        if (this.#freed) return;
        this.grammar.runtime.abi.arborium_rt_free_session(this.id);
        this.#freed = true;
    }

    #assertLive(): void {
        if (this.#freed) {
            throw new ArboriumError(
                'session-creation-failed',
                `session ${this.id} has been freed`,
            );
        }
    }
}

// ---------------------------------------------------------------------------
// internals
// ---------------------------------------------------------------------------

function pickLanguageExport(
    exports: Record<string, unknown>,
    name: string | undefined,
): (...args: number[]) => number {
    if (name !== undefined) {
        const fn = exports[name];
        if (typeof fn !== 'function') {
            throw new ArboriumError(
                'grammar-language-export-missing',
                `grammar module has no function export named ${JSON.stringify(name)}`,
            );
        }
        return fn as (...args: number[]) => number;
    }
    const candidates = Object.keys(exports).filter(
        (k) => k.startsWith('tree_sitter_') && typeof exports[k] === 'function',
    );
    if (candidates.length === 0) {
        throw new ArboriumError(
            'grammar-language-export-missing',
            'grammar module has no function export starting with tree_sitter_',
        );
    }
    if (candidates.length > 1) {
        throw new ArboriumError(
            'grammar-language-export-missing',
            `grammar module has multiple tree_sitter_* exports: ${candidates.join(', ')}. Pass options.languageExport to disambiguate.`,
        );
    }
    // Safe: candidates[0] is defined (we just checked length === 1).
    return exports[candidates[0]!] as (...args: number[]) => number;
}
