// Build-time packer for one grammar.
//
// Compiled together with a generated parser.c (see `build wasm grammar`):
//
//   emcc -DTS_PACKED_GRAMMAR_HEADER -DTS_PACKED_ENCODER
//        -DPARSER_C='"src/parser.c"' -DLANGUAGE_SYMBOL=cpp -Isrc
//        pack.c ts_packed.c -o pack.mjs
//   node pack.mjs <out.c>
//
// It encodes the language's tables and lex programs, decodes them again and
// checks the tables match the original byte for byte and the lex programs
// behave exactly like the compiled lex functions, then writes a C file whose
// `tree_sitter_<lang>()` loads the packed
// tables. The C file doesn't include parser.c: the lex functions ship as
// data too (TREE_SITTER_LEX_PROGRAM, patches/tree-sitter/0003) and run
// through the host's ts_packed_lex(), so only the external scanner (if any)
// remains compiled code.

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define STR2(x) #x
#define STR(x) STR2(x)
#define CAT2(a, b) a##b
#define CAT(a, b) CAT2(a, b)

#define TREE_SITTER_LEX_PROGRAM
#include PARSER_C

#include "ts_packed.h"

typedef struct {
  const uint32_t *main;
  size_t main_len;
  const uint32_t *keywords;
  size_t keywords_len;
  const uint32_t *sets;
  size_t sets_len;
} TSPackedLexSource;

uint8_t *ts_packed_encode(const TSLanguage *L, const TSPackedLexSource *lex, size_t *length, const char **error);
bool ts_packed_verify(const TSLanguage *L, const uint8_t *blob, size_t length, const char **error);

#ifdef TREE_SITTER_LEX_KEYWORDS_PROGRAM
#define KEYWORDS_PROGRAM TREE_SITTER_LEX_KEYWORDS_PROGRAM
#define KEYWORDS_PROGRAM_LEN (sizeof TREE_SITTER_LEX_KEYWORDS_PROGRAM / sizeof *TREE_SITTER_LEX_KEYWORDS_PROGRAM)
#else
#define KEYWORDS_PROGRAM NULL
#define KEYWORDS_PROGRAM_LEN 0
#endif

int main(int argc, char **argv) {
  if (argc != 2) {
    fprintf(stderr, "usage: pack <out.c>\n");
    return 2;
  }
  const char *name = STR(LANGUAGE_SYMBOL);
  const TSLanguage *L = CAT(tree_sitter_, LANGUAGE_SYMBOL)();

  // ts_lex_keywords_program only exists when the grammar has a keyword lexer.
  TSPackedLexSource lex = {
    ts_lex_program, sizeof ts_lex_program / sizeof *ts_lex_program,
    KEYWORDS_PROGRAM, KEYWORDS_PROGRAM_LEN,
    ts_lex_character_sets, sizeof ts_lex_character_sets / sizeof *ts_lex_character_sets,
  };
  size_t length = 0;
  const char *error = NULL;
  uint8_t *blob = ts_packed_encode(L, &lex, &length, &error);
  if (!blob) {
    fprintf(stderr, "pack %s: %s\n", name, error ? error : "failed");
    return 1;
  }
  if (!ts_packed_verify(L, blob, length, &error)) {
    fprintf(stderr, "pack %s: decoded tables differ from the original: %s\n", name, error);
    return 1;
  }

  FILE *f = fopen(argv[1], "w");
  if (!f) {
    perror(argv[1]);
    return 1;
  }
  fprintf(f, "// Generated by arborium-rt (lib/packed/pack.c). Do not edit.\n");
  fprintf(f, "// tree_sitter_%s(): tables and lexers packed into %zu bytes.\n\n", name, length);
  fprintf(f, "#include \"tree_sitter/parser.h\"\n");
  fprintf(f, "#include \"ts_packed.h\"\n\n");
  fprintf(f, "#ifdef _WIN32\n#define TS_PUBLIC __declspec(dllexport)\n#else\n#define TS_PUBLIC __attribute__((visibility(\"default\")))\n#endif\n\n");
  bool scanner = L->external_scanner.create != NULL;
  if (scanner) {
    fprintf(f, "void *tree_sitter_%s_external_scanner_create(void);\n", name);
    fprintf(f, "void tree_sitter_%s_external_scanner_destroy(void *);\n", name);
    fprintf(f, "bool tree_sitter_%s_external_scanner_scan(void *, TSLexer *, const bool *);\n", name);
    fprintf(f, "unsigned tree_sitter_%s_external_scanner_serialize(void *, char *);\n", name);
    fprintf(f, "void tree_sitter_%s_external_scanner_deserialize(void *, const char *, unsigned);\n\n", name);
  }
  fprintf(f, "static const uint8_t ts_packed_tables[%zu] = {", length);
  for (size_t i = 0; i < length; i++) {
    fprintf(f, "%s%u,", i % 24 ? "" : "\n  ", blob[i]);
  }
  fprintf(f, "\n};\n\n");
  fprintf(f, "static const TSPackedLexer *ts_lex_program;\n");
  fprintf(f, "static bool ts_lex(TSLexer *lexer, TSStateId state) {\n");
  fprintf(f, "  return ts_packed_lex(ts_lex_program, lexer, state);\n}\n\n");
  if (L->keyword_lex_fn) {
    fprintf(f, "static const TSPackedLexer *ts_lex_keywords_program;\n");
    fprintf(f, "static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {\n");
    fprintf(f, "  return ts_packed_lex(ts_lex_keywords_program, lexer, state);\n}\n\n");
  }
  fprintf(f, "TS_PUBLIC const TSLanguage *tree_sitter_%s(void) {\n", name);
  fprintf(f, "  static const TSLanguage *language;\n");
  fprintf(f, "  if (!language) {\n");
  fprintf(f, "    static const TSPackedFunctions functions = {\n");
  fprintf(f, "      .lex_fn = ts_lex,\n");
  fprintf(f, "      .lex_program = &ts_lex_program,\n");
  if (L->keyword_lex_fn) {
    fprintf(f, "      .keyword_lex_fn = ts_lex_keywords,\n");
    fprintf(f, "      .keyword_lex_program = &ts_lex_keywords_program,\n");
  }
  if (scanner) {
    static const char *const ops[] = {"create", "destroy", "scan", "serialize", "deserialize"};
    for (int i = 0; i < 5; i++) {
      fprintf(f, "      .external_scanner_%s = tree_sitter_%s_external_scanner_%s,\n", ops[i], name, ops[i]);
    }
  }
  fprintf(f, "    };\n");
  fprintf(f, "    language = ts_packed_language_load(ts_packed_tables, sizeof(ts_packed_tables), &functions);\n");
  fprintf(f, "  }\n");
  fprintf(f, "  return language;\n");
  fprintf(f, "}\n");
  if (fclose(f)) {
    perror(argv[1]);
    return 1;
  }
#ifdef TS_PACKED_STATS
  {
    extern double g_stat_bits[256];
    extern uint64_t g_stat_count[256];
    for (int i = 0; i < 256; i++) {
      if (g_stat_count[i]) fprintf(stderr, "  comp %3d: %9.0f bytes %9llu decisions\n", i, g_stat_bits[i] / 8, (unsigned long long)g_stat_count[i]);
    }
  }
#endif
  printf("%zu\n", length);
  free(blob);
  return 0;
}
