// Build-time packer for one grammar.
//
// Compiled together with a generated parser.c (see `build wasm grammar`):
//
//   emcc -DTS_PACKED_GRAMMAR_HEADER -DTS_PACKED_ENCODER
//        -DPARSER_C='"src/parser.c"' -DLANGUAGE_SYMBOL=cpp -Isrc
//        pack.c ts_packed.c -o pack.mjs
//   node pack.mjs <out.c>
//
// It encodes the language's tables, decodes them again and checks the result
// matches the original byte for byte, then writes a C file that includes
// parser.c and replaces `tree_sitter_<lang>()` with one that loads the packed
// tables. Linking that file instead of parser.c leaves the original tables
// unreferenced, so they're dropped from the wasm.

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define STR2(x) #x
#define STR(x) STR2(x)
#define CAT2(a, b) a##b
#define CAT(a, b) CAT2(a, b)

#include PARSER_C

#include "ts_packed.h"

uint8_t *ts_packed_encode(const TSLanguage *L, size_t *length, const char **error);
bool ts_packed_verify(const TSLanguage *L, const uint8_t *blob, size_t length, const char **error);

int main(int argc, char **argv) {
  if (argc != 2) {
    fprintf(stderr, "usage: pack <out.c>\n");
    return 2;
  }
  const char *name = STR(LANGUAGE_SYMBOL);
  const TSLanguage *L = CAT(tree_sitter_, LANGUAGE_SYMBOL)();

  size_t length = 0;
  const char *error = NULL;
  uint8_t *blob = ts_packed_encode(L, &length, &error);
  if (!blob) {
    fprintf(stderr, "pack %s: %s\n", name, error ? error : "failed");
    return 1;
  }
  if (!ts_packed_verify(L, blob, length, &error)) {
    fprintf(stderr, "pack %s: decoded tables differ from the original: %s\n", name, error);
    return 1;
  }

  FILE *f = fopen(argv[1], "w");
  if (!f) {
    perror(argv[1]);
    return 1;
  }
  fprintf(f, "// Generated by arborium-rt (lib/packed/pack.c). Do not edit.\n");
  fprintf(f, "// tree_sitter_%s() with its tables packed into %zu bytes.\n\n", name, length);
  fprintf(f, "#define tree_sitter_%s tree_sitter_%s__unpacked\n", name, name);
  fprintf(f, "#include \"parser.c\"\n");
  fprintf(f, "#undef tree_sitter_%s\n\n", name);
  fprintf(f, "#include \"ts_packed.h\"\n\n");
  fprintf(f, "static const uint8_t ts_packed_tables[%zu] = {", length);
  for (size_t i = 0; i < length; i++) {
    fprintf(f, "%s%u,", i % 24 ? "" : "\n  ", blob[i]);
  }
  fprintf(f, "\n};\n\n");
  fprintf(f, "TS_PUBLIC const TSLanguage *tree_sitter_%s(void) {\n", name);
  fprintf(f, "  static const TSLanguage *language;\n");
  fprintf(f, "  if (!language) {\n");
  fprintf(f, "    static const TSPackedFunctions functions = {\n");
  fprintf(f, "      .lex_fn = ts_lex,\n");
  if (L->keyword_lex_fn) fprintf(f, "      .keyword_lex_fn = ts_lex_keywords,\n");
  if (L->external_scanner.create) {
    static const char *const ops[] = {"create", "destroy", "scan", "serialize", "deserialize"};
    for (int i = 0; i < 5; i++) {
      fprintf(f, "      .external_scanner_%s = tree_sitter_%s_external_scanner_%s,\n", ops[i], name, ops[i]);
    }
  }
  fprintf(f, "    };\n");
  fprintf(f, "    language = ts_packed_language_load(ts_packed_tables, sizeof(ts_packed_tables), &functions);\n");
  fprintf(f, "  }\n");
  fprintf(f, "  return language;\n");
  fprintf(f, "}\n");
  if (fclose(f)) {
    perror(argv[1]);
    return 1;
  }
#ifdef TS_PACKED_STATS
  {
    extern double g_stat_bits[256];
    extern uint64_t g_stat_count[256];
    for (int i = 0; i < 256; i++) {
      if (g_stat_count[i]) fprintf(stderr, "  comp %3d: %9.0f bytes %9llu decisions\n", i, g_stat_bits[i] / 8, (unsigned long long)g_stat_count[i]);
    }
  }
#endif
  printf("%zu\n", length);
  free(blob);
  return 0;
}
