// Emit a per-grammar subdir into the runtime package's dist/grammars/<lang>/,
// consumed via the subpath export `@appellation/arborium-rt/grammars/<lang>`.
//
// Output per grammar: index.js, index.d.ts, tree-sitter-<lang>.wasm, and any
// flattened `.scm` files the grammar ships. No separate package.json — these
// subdirs are just assets of the runtime package.

import {
    copyFileSync,
    existsSync,
    mkdirSync,
    readFileSync,
    rmSync,
    statSync,
    writeFileSync,
} from 'node:fs';
import { join, relative } from 'node:path';

import { buildGrammarIndex } from './arborium-yaml.js';
import { QUERY_TYPES, type QueryType } from './flatten.js';
import { paths, step } from './util.js';

export interface BuildPackageArgs {
    group: string;
    lang: string;
}

export async function buildPackage(args: BuildPackageArgs): Promise<void> {
    const p = paths();
    const grammarDir = join(p.grammarsOut, args.lang);
    const outDir = join(p.packagesOut, args.lang);
    const wasmName = `tree-sitter-${args.lang}.wasm`;
    const wasmSrc = join(grammarDir, wasmName);

    if (!existsSync(wasmSrc)) {
        throw new Error(
            `${wasmSrc} not found. run \`arborium-rt build-grammar ${args.group} ${args.lang}\` first.`,
        );
    }

    const index = buildGrammarIndex(p.langsRoot);
    const entry = index.get(args.lang);
    const cSymbol = entry?.grammar.c_symbol ?? args.lang;

    const queries: Partial<Record<QueryType, string>> = {};
    for (const qtype of QUERY_TYPES) {
        const src = join(grammarDir, `${qtype}.scm`);
        if (existsSync(src)) {
            queries[qtype] = readFileSync(src, 'utf8');
        }
    }

    rmSync(outDir, { recursive: true, force: true });
    mkdirSync(outDir, { recursive: true });

    copyFileSync(wasmSrc, join(outDir, wasmName));
    for (const [qtype, content] of Object.entries(queries)) {
        writeFileSync(join(outDir, `${qtype}.scm`), content);
    }

    const languageExport = `tree_sitter_${cSymbol}`;
    writeFileSync(
        join(outDir, 'index.js'),
        renderIndexJs(args.lang, languageExport, wasmName, queries),
    );
    writeFileSync(
        join(outDir, 'index.d.ts'),
        renderIndexDts(args.lang, languageExport, queries),
    );

    step(`wrote grammars/${args.lang} to ${relative(p.repoRoot, outDir)}`);
    for (const name of ['index.js', 'index.d.ts', wasmName]) {
        const size = statSync(join(outDir, name)).size;
        console.error(`    ${size.toString().padStart(9)}  ${name}`);
    }
}

function renderIndexJs(
    lang: string,
    languageExport: string,
    wasmName: string,
    queries: Partial<Record<QueryType, string>>,
): string {
    const lines: string[] = [
        '// AUTO-GENERATED by `arborium-rt package` — do not edit.',
        `// Grammar subpath for @appellation/arborium-rt/grammars/${lang}.`,
        '',
        `const wasm = new URL(${JSON.stringify(`./${wasmName}`)}, import.meta.url);`,
        '',
    ];
    for (const qtype of QUERY_TYPES) {
        const content = queries[qtype];
        if (content !== undefined) {
            lines.push(`const ${qtype} = ${JSON.stringify(content)};`);
        }
    }
    if (Object.keys(queries).length > 0) lines.push('');
    lines.push('export default {');
    lines.push(`    languageId: ${JSON.stringify(lang)},`);
    lines.push(`    languageExport: ${JSON.stringify(languageExport)},`);
    lines.push('    wasm,');
    for (const qtype of QUERY_TYPES) {
        if (queries[qtype] !== undefined) lines.push(`    ${qtype},`);
    }
    lines.push('};');
    lines.push('');
    return lines.join('\n');
}

function renderIndexDts(
    lang: string,
    languageExport: string,
    queries: Partial<Record<QueryType, string>>,
): string {
    const lines: string[] = [
        '// AUTO-GENERATED by `arborium-rt package` — do not edit.',
        '',
        'declare const grammar: {',
        `    readonly languageId: ${JSON.stringify(lang)};`,
        `    readonly languageExport: ${JSON.stringify(languageExport)};`,
        '    readonly wasm: URL;',
    ];
    for (const qtype of QUERY_TYPES) {
        if (queries[qtype] !== undefined) {
            lines.push(`    readonly ${qtype}: string;`);
        }
    }
    lines.push('};');
    lines.push('export default grammar;');
    lines.push('');
    return lines.join('\n');
}
