// Generate target/packages/<lang>/ as a publishable @appellation/arborium-rt-<lang>.
// Port of `scripts/build-grammar-package.py`.

import {
    copyFileSync,
    existsSync,
    mkdirSync,
    readFileSync,
    rmSync,
    statSync,
    writeFileSync,
} from 'node:fs';
import { join, relative } from 'node:path';

import { buildGrammarIndex } from './arborium-yaml.js';
import { QUERY_TYPES, type QueryType } from './flatten.js';
import { paths, step } from './util.js';

export interface BuildPackageArgs {
    group: string;
    lang: string;
    version: string;
}

export async function buildPackage(args: BuildPackageArgs): Promise<void> {
    const p = paths();
    const grammarDir = join(p.grammarsOut, args.lang);
    const outDir = join(p.packagesOut, args.lang);
    const wasmName = `tree-sitter-${args.lang}.wasm`;
    const wasmSrc = join(grammarDir, wasmName);

    if (!existsSync(wasmSrc)) {
        throw new Error(
            `${wasmSrc} not found. run \`arborium-rt build-grammar ${args.group} ${args.lang}\` first.`,
        );
    }

    const index = buildGrammarIndex(p.langsRoot);
    const entry = index.get(args.lang);
    const displayName = entry?.grammar.name ?? args.lang;
    const aliases = entry?.grammar.aliases ?? [];
    const cSymbol = entry?.grammar.c_symbol ?? args.lang;

    // Gather contributing query files
    const queries: Partial<Record<QueryType, string>> = {};
    for (const qtype of QUERY_TYPES) {
        const src = join(grammarDir, `${qtype}.scm`);
        if (existsSync(src)) {
            queries[qtype] = readFileSync(src, 'utf8');
        }
    }

    // Clean-slate the output dir
    rmSync(outDir, { recursive: true, force: true });
    mkdirSync(outDir, { recursive: true });

    copyFileSync(wasmSrc, join(outDir, wasmName));
    for (const [qtype, content] of Object.entries(queries)) {
        writeFileSync(join(outDir, `${qtype}.scm`), content);
    }

    const languageExport = `tree_sitter_${cSymbol}`;
    writeFileSync(
        join(outDir, 'index.js'),
        renderIndexJs(args.lang, languageExport, wasmName, queries),
    );
    writeFileSync(
        join(outDir, 'index.d.ts'),
        renderIndexDts(args.lang, languageExport, queries),
    );
    writeFileSync(
        join(outDir, 'package.json'),
        JSON.stringify(
            renderPackageJson(args.lang, displayName, aliases, args.version, wasmName, queries),
            null,
            2,
        ) + '\n',
    );
    writeFileSync(join(outDir, 'README.md'), renderReadme(args.lang, displayName));

    step(`wrote @appellation/arborium-rt-${args.lang} to ${relative(p.repoRoot, outDir)}`);
    for (const entry of ['package.json', 'index.js', 'index.d.ts', wasmName]) {
        const size = statSync(join(outDir, entry)).size;
        console.error(`    ${size.toString().padStart(9)}  ${entry}`);
    }
}

function renderIndexJs(
    lang: string,
    languageExport: string,
    wasmName: string,
    queries: Partial<Record<QueryType, string>>,
): string {
    const lines: string[] = [
        '// AUTO-GENERATED by `arborium-rt package` — do not edit.',
        `// Grammar package for @appellation/arborium-rt: ${lang}`,
        '',
        `const wasm = new URL(${JSON.stringify(`./${wasmName}`)}, import.meta.url);`,
        '',
    ];
    for (const qtype of QUERY_TYPES) {
        const content = queries[qtype];
        if (content !== undefined) {
            // JSON.stringify produces a valid JS string literal — handles
            // newlines, backslashes, quotes, non-BMP characters.
            lines.push(`const ${qtype} = ${JSON.stringify(content)};`);
        }
    }
    if (Object.keys(queries).length > 0) lines.push('');
    lines.push('export default {');
    lines.push(`    languageId: ${JSON.stringify(lang)},`);
    lines.push(`    languageExport: ${JSON.stringify(languageExport)},`);
    lines.push('    wasm,');
    for (const qtype of QUERY_TYPES) {
        if (queries[qtype] !== undefined) lines.push(`    ${qtype},`);
    }
    lines.push('};');
    lines.push('');
    return lines.join('\n');
}

function renderIndexDts(
    lang: string,
    languageExport: string,
    queries: Partial<Record<QueryType, string>>,
): string {
    const lines: string[] = [
        '// AUTO-GENERATED by `arborium-rt package` — do not edit.',
        '',
        'declare const grammar: {',
        `    readonly languageId: ${JSON.stringify(lang)};`,
        `    readonly languageExport: ${JSON.stringify(languageExport)};`,
        '    readonly wasm: URL;',
    ];
    for (const qtype of QUERY_TYPES) {
        if (queries[qtype] !== undefined) {
            lines.push(`    readonly ${qtype}: string;`);
        }
    }
    lines.push('};');
    lines.push('export default grammar;');
    lines.push('');
    return lines.join('\n');
}

function renderPackageJson(
    lang: string,
    displayName: string,
    aliases: string[],
    version: string,
    wasmName: string,
    queries: Partial<Record<QueryType, string>>,
): Record<string, unknown> {
    const exportsMap: Record<string, unknown> = {
        '.': {
            types: './index.d.ts',
            default: './index.js',
        },
        [`./${wasmName}`]: `./${wasmName}`,
    };
    const files = ['index.js', 'index.d.ts', wasmName];
    for (const qtype of QUERY_TYPES) {
        if (queries[qtype] !== undefined) {
            files.push(`${qtype}.scm`);
            exportsMap[`./${qtype}.scm`] = `./${qtype}.scm`;
        }
    }
    return {
        name: `@appellation/arborium-rt-${lang}`,
        version,
        description: `${displayName} grammar for @appellation/arborium-rt`,
        license: 'MIT',
        type: 'module',
        main: './index.js',
        types: './index.d.ts',
        exports: exportsMap,
        files,
        keywords: ['tree-sitter', 'syntax-highlighting', 'arborium', lang, ...aliases],
        peerDependencies: {
            '@appellation/arborium-rt': `^${version}`,
        },
        repository: {
            type: 'git',
            url: 'git+https://github.com/appellation/arborium-rt.git',
        },
        publishConfig: {
            registry: 'https://npm.pkg.github.com',
        },
    };
}

function renderReadme(lang: string, displayName: string): string {
    return `# @appellation/arborium-rt-${lang}

${displayName} grammar for [\`@appellation/arborium-rt\`](https://github.com/appellation/arborium-rt).

## Usage

\`\`\`ts
import { loadArboriumRuntime } from '@appellation/arborium-rt';
import hostModuleFactory from '@appellation/arborium-rt/host-module';
import ${lang}Grammar from '@appellation/arborium-rt-${lang}';

const runtime = await loadArboriumRuntime({
    hostModuleFactory,
    runtimeWasm: fetch(
        new URL('@appellation/arborium-rt/runtime-wasm', import.meta.url),
    ),
});

const grammar = await runtime.loadGrammar(${lang}Grammar);
const session = grammar.createSession();
session.setText('...');
const { spans } = session.parse();
\`\`\`

Generated by \`arborium-rt package\`. See the repo root for how the wasm +
queries are produced.
`;
}
