// Generate packages/arborium-rt/src/grammars.ts — the single module that
// lists every bundled grammar's metadata (id, languageExport, asset URLs).
// Compiled by tsc to dist/grammars.js, sibling to the dist/grammars/
// subdir that `buildPackage` populates with per-language .wasm/.scm files,
// so the emitted `new URL('./grammars/<lang>/…', import.meta.url)`
// references resolve directly.

import { existsSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { buildGrammarIndex } from './arborium-yaml.js';
import { QUERY_TYPES, type QueryType } from './flatten.js';
import { paths } from './util.js';

interface Entry {
    readonly lang: string;
    readonly languageExport: string;
    readonly queries: ReadonlySet<QueryType>;
}

export function writeGrammarsIndexModule(): void {
    const p = paths();
    const index = buildGrammarIndex(p.langsRoot);
    const entries = scanEntries(p.packagesOut, index);

    writeFileSync(join(p.runtimePackageDir, 'src', 'grammars.ts'), renderModule(entries));
}

function scanEntries(
    packagesOut: string,
    index: ReturnType<typeof buildGrammarIndex>,
): Entry[] {
    if (!existsSync(packagesOut)) return [];
    const langs = readdirSync(packagesOut)
        .filter((name) => statSync(join(packagesOut, name)).isDirectory())
        .filter((name) => existsSync(join(packagesOut, name, `tree-sitter-${name}.wasm`)))
        .sort();

    return langs.map((lang) => {
        const queries = new Set<QueryType>();
        for (const qtype of QUERY_TYPES) {
            if (existsSync(join(packagesOut, lang, `${qtype}.scm`))) queries.add(qtype);
        }
        const cSymbol = index.get(lang)?.grammar.c_symbol ?? lang;
        return { lang, languageExport: `tree_sitter_${cSymbol}`, queries };
    });
}

function renderModule(entries: readonly Entry[]): string {
    const lines: string[] = [
        '// AUTO-GENERATED by `arborium-rt package` — do not edit.',
        '// Regenerated from the grammar subdirs currently under dist/grammars/.',
        '',
        'import type { ArboriumGrammarPackage } from \'./runtime.js\';',
        '',
        '/**',
        ' * Every bundled grammar keyed by language id. Entries ship eagerly —',
        ' * each is a handful of bytes of metadata plus `URL`s pointing at the',
        ' * per-grammar `.wasm` and `.scm` assets sitting under `./grammars/`.',
        ' * The actual bytes are only fetched when `loadGrammar` is called.',
        ' */',
        'export const GRAMMARS = {',
    ];
    for (const entry of entries) {
        lines.push(`    ${JSON.stringify(entry.lang)}: {`);
        lines.push(`        languageId: ${JSON.stringify(entry.lang)},`);
        lines.push(`        languageExport: ${JSON.stringify(entry.languageExport)},`);
        lines.push(`        wasm: new URL(${JSON.stringify(`./grammars/${entry.lang}/tree-sitter-${entry.lang}.wasm`)}, import.meta.url),`);
        lines.push(`        highlights: new URL(${JSON.stringify(`./grammars/${entry.lang}/highlights.scm`)}, import.meta.url),`);
        for (const qtype of QUERY_TYPES) {
            if (qtype === 'highlights') continue;
            if (entry.queries.has(qtype)) {
                lines.push(`        ${qtype}: new URL(${JSON.stringify(`./grammars/${entry.lang}/${qtype}.scm`)}, import.meta.url),`);
            }
        }
        lines.push('    },');
    }
    lines.push('} as const;');
    lines.push('');
    lines.push('/** Synonym for callers that want the package shape without the const narrowing. */');
    lines.push('export type BundledGrammarId = keyof typeof GRAMMARS;');
    lines.push('');
    return lines.join('\n');
}
