// Generate packages/arborium-rt/src/themes.ts — the single module that lists
// every bundled theme's metadata plus a URL pointing at the staged `.css`
// file under dist/themes/. Compiled by tsc to dist/themes.js, sibling to
// the `dist/themes/<id>.css` files written by the `stage` step.

import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { paths } from './util.js';

export interface ThemeIndexEntry {
    readonly themeId: string;
    readonly name: string;
    readonly variant: 'dark' | 'light';
    readonly background?: string;
    readonly foreground?: string;
}

export function writeThemesIndexModule(entries: readonly ThemeIndexEntry[]): void {
    const p = paths();
    const srcDir = join(p.runtimePackageDir, 'src');
    mkdirSync(srcDir, { recursive: true });
    writeFileSync(join(srcDir, 'themes.ts'), renderModule(entries));
}

function renderModule(entries: readonly ThemeIndexEntry[]): string {
    const lines: string[] = [
        '// AUTO-GENERATED by `arborium-rt stage` — do not edit.',
        '// Regenerated from arborium_theme::theme::builtin::all_with_ids() via',
        '// the crates/theme-codegen host binary.',
        '',
        '/**',
        ' * Stable shape for each entry in the bundled `THEMES` map exported',
        ' * from `@discord/arborium-rt`. `css` is a `URL` pointing at a',
        ' * standalone stylesheet scoped under `.arborium-<themeId>` — import',
        ' * as a sibling stylesheet or fetch + inject at runtime.',
        ' */',
        'export interface ArboriumThemePackage {',
        '    /** Kebab-case theme id (TOML filename stem in arborium-theme). */',
        '    themeId: string;',
        '    /** Display name from the theme\'s `name = "..."` field. */',
        '    name: string;',
        '    /** Whether the theme targets a dark or light editor background. */',
        '    variant: "dark" | "light";',
        '    /** Background hex, if the theme declared one. */',
        '    background?: string;',
        '    /** Foreground hex, if the theme declared one. */',
        '    foreground?: string;',
        '    /** `URL` to the pre-rendered `.css` file scoped under `.arborium-<themeId>`. */',
        '    css: URL;',
        '}',
        '',
        '/**',
        ' * Every bundled theme keyed by id. Each entry is a handful of bytes',
        ' * of metadata plus a `URL` pointing at `./themes/<id>.css`. CSS',
        ' * bytes are only fetched when a caller dereferences `entry.css`.',
        ' */',
        'export const THEMES = {',
    ];
    for (const entry of entries) {
        lines.push(`    ${JSON.stringify(entry.themeId)}: {`);
        lines.push(`        themeId: ${JSON.stringify(entry.themeId)},`);
        lines.push(`        name: ${JSON.stringify(entry.name)},`);
        lines.push(`        variant: ${JSON.stringify(entry.variant)},`);
        if (entry.background !== undefined) {
            lines.push(`        background: ${JSON.stringify(entry.background)},`);
        }
        if (entry.foreground !== undefined) {
            lines.push(`        foreground: ${JSON.stringify(entry.foreground)},`);
        }
        lines.push(`        css: new URL(${JSON.stringify(`./themes/${entry.themeId}.css`)}, import.meta.url),`);
        lines.push('    },');
    }
    lines.push('} as const satisfies Record<string, ArboriumThemePackage>;');
    lines.push('');
    lines.push('/** Union of every bundled theme id. */');
    lines.push('export type BundledThemeId = keyof typeof THEMES;');
    lines.push('');
    return lines.join('\n');
}
