// Generate packages/arborium-rt-wasm/src/grammars.ts — the single module that
// lists every bundled grammar's metadata (id, languageExport, asset URLs).
// Compiled by tsc to dist/grammars.js, sibling to the dist/grammars/
// subdir that `packageGrammar` populates with per-language .wasm/.scm files,
// so the emitted `new URL('./grammars/<lang>/…', import.meta.url)`
// references resolve directly.

import { readdir, stat, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { buildGrammarIndex } from "./arborium-yaml.ts";
import { QUERY_TYPES, type QueryType } from "./flatten.ts";
import { normalizeCSymbol, paths } from "./util.ts";

interface Entry {
	readonly lang: string;
	readonly languageExport: string;
	readonly queries: ReadonlySet<QueryType>;
}

const isFile = (file: string): Promise<boolean> =>
	stat(file).then(
		(s) => s.isFile(),
		() => false,
	);

const isDir = (dir: string): Promise<boolean> =>
	stat(dir).then(
		(s) => s.isDirectory(),
		() => false,
	);

export async function writeGrammarsIndexModule(): Promise<void> {
	const p = paths();
	const index = await buildGrammarIndex(p.langsRoots);
	const entries = await scanEntries(p.packagesOut, index);

	await writeFile(
		join(p.runtimePackageDir, "src", "grammars.ts"),
		renderModule(entries),
	);
}

async function scanEntries(
	packagesOut: string,
	index: Awaited<ReturnType<typeof buildGrammarIndex>>,
): Promise<Entry[]> {
	let names: string[];
	try {
		names = await readdir(packagesOut);
	} catch {
		return [];
	}

	const candidates = await Promise.all(
		names.sort().map(async (name) => {
			const ok =
				(await isDir(join(packagesOut, name))) &&
				(await isFile(join(packagesOut, name, `tree-sitter-${name}.wasm`)));
			return ok ? name : null;
		}),
	);
	const langs = candidates.filter((name): name is string => name !== null);

	return Promise.all(
		langs.map(async (lang) => {
			const queries = new Set<QueryType>();
			for (const qtype of QUERY_TYPES) {
				if (await isFile(join(packagesOut, lang, `${qtype}.scm`)))
					queries.add(qtype);
			}
			const cSymbol = normalizeCSymbol(index.get(lang)?.grammar.c_symbol, lang);
			return { lang, languageExport: `tree_sitter_${cSymbol}`, queries };
		}),
	);
}

function renderModule(entries: readonly Entry[]): string {
	const lines: string[] = [
		"// AUTO-GENERATED by `arborium-rt package` — do not edit.",
		"// Regenerated from the grammar subdirs currently under dist/grammars/.",
		"",
		"import type { ArboriumGrammarPackage } from './runtime.js';",
		"",
		"/**",
		" * Every bundled grammar keyed by language id. Entries ship eagerly —",
		" * each is a handful of bytes of metadata plus `URL`s pointing at the",
		" * per-grammar `.wasm` and `.scm` assets sitting under `./grammars/`.",
		" * The actual bytes are only fetched when `loadGrammar` is called.",
		" */",
		"export const GRAMMARS = {",
	];
	for (const entry of entries) {
		lines.push(`    ${JSON.stringify(entry.lang)}: {`);
		lines.push(`        languageId: ${JSON.stringify(entry.lang)},`);
		lines.push(
			`        languageExport: ${JSON.stringify(entry.languageExport)},`,
		);
		lines.push(
			`        wasm: new URL(${JSON.stringify(`./grammars/${entry.lang}/tree-sitter-${entry.lang}.wasm`)}, import.meta.url),`,
		);
		lines.push(
			`        highlights: new URL(${JSON.stringify(`./grammars/${entry.lang}/highlights.scm`)}, import.meta.url),`,
		);
		for (const qtype of QUERY_TYPES) {
			if (qtype === "highlights") continue;
			if (entry.queries.has(qtype)) {
				lines.push(
					`        ${qtype}: new URL(${JSON.stringify(`./grammars/${entry.lang}/${qtype}.scm`)}, import.meta.url),`,
				);
			}
		}
		lines.push("    },");
	}
	lines.push("} as const;");
	lines.push("");
	lines.push(
		"/** Synonym for callers that want the package shape without the const narrowing. */",
	);
	lines.push("export type BundledGrammarId = keyof typeof GRAMMARS;");
	lines.push("");
	return lines.join("\n");
}
