//! Shared native core for arborium-rt's statically-linked targets.
//!
//! Every grammar's `parser.c`/scanner is compiled into this crate (see
//! `build.rs`) and its flattened queries are baked in as `&'static str`. The
//! FFI shims (`ffi/node`, `ffi/android`, …) depend on this crate, call
//! [`register_all`] once, and then drive the shared
//! [`arborium_rt::highlight`] pipeline against
//! [`arborium_rt::registry`]. This crate has no FFI surface and no
//! target-specific dependencies — each target wraps it in its own boundary
//! (napi / jni / C-ABI).
//!
//! The registry is a single process-global mutex, populated exactly once by
//! [`register_all`] and immutable afterward (no `unregister` — everything is
//! static). The one-time `OnceLock` init keeps concurrent first-touch safe.

use std::collections::HashMap;
use std::sync::OnceLock;

use arborium_rt::registry::registry;
use arborium_tree_sitter::Language;

/// One statically-linked grammar. `lang_fn` is the grammar's
/// `tree_sitter_<cSymbol>()` C export; the queries are the flattened `.scm`
/// text (empty string when the grammar has none of that type).
struct GrammarDef {
    id: &'static str,
    lang_fn: unsafe extern "C" fn() -> *const ::core::ffi::c_void,
    highlights: &'static str,
    injections: &'static str,
    locals: &'static str,
}

// Generated by build.rs: the `extern "C"` block of `tree_sitter_*` decls and
// the `GRAMMARS: &[GrammarDef]` table.
include!(concat!(env!("OUT_DIR"), "/grammar_table.rs"));

/// Register every bundled grammar into the global registry exactly once, and
/// return the resulting `language id -> grammar id` map. Registration happens
/// under the registry mutex (required by the `PENDING_LANG` handoff in
/// `register_grammar`). Idempotent: subsequent calls return the cached map.
pub fn register_all() -> &'static HashMap<String, u32> {
    static IDS: OnceLock<HashMap<String, u32>> = OnceLock::new();
    IDS.get_or_init(|| {
        let mut reg = registry().lock().expect("registry poisoned");
        let mut ids = HashMap::with_capacity(GRAMMARS.len());
        for g in GRAMMARS {
            // SAFETY: lang_fn is a grammar's `tree_sitter_<sym>()` export,
            // linked into this build; it returns a pointer to a `'static`
            // const TSLanguage valid for the process lifetime.
            let raw = unsafe { (g.lang_fn)() };
            if raw.is_null() {
                continue;
            }
            let language = unsafe { Language::from_raw(raw.cast()) };
            match reg.register_grammar(g.id, language, g.highlights, g.injections, g.locals) {
                Ok(gid) => {
                    ids.insert(g.id.to_string(), gid);
                }
                Err(_) => {
                    // A grammar whose query fails to compile is skipped rather
                    // than aborting the whole target; it simply won't be in the
                    // available-languages set.
                }
            }
        }
        ids
    })
}

/// The ids of every bundled grammar, sorted. Convenience over [`register_all`].
pub fn available_languages() -> Vec<String> {
    let mut v: Vec<String> = register_all().keys().cloned().collect();
    v.sort();
    v
}
